### ISSUE TITLE
Build fail in rust-stable

### ISSUE THREAD

**Issue by kination** [lychee-eng/parenchyma#1]
Hello~
`cargo build` cause fail in stable rust version(nightly works fine).

```
error[E0001]: unreachable pattern
  --> src/api/memory.rs:22:4
   |
22 | 			_ => Err(Error::memory("Expected `Native` memory (`FlatBox`).")),
   | 			^ this is an unreachable pattern

error[E0001]: unreachable pattern
  --> src/api/memory.rs:33:4
   |
33 | 			_ => Err(Error::memory("Expected `Native` memory (`FlatBox`).")),
   | 			^ this is an unreachable pattern

error: aborting due to 2 previous errors
```
Could you look on it?

**Comment by jonysy** [comment]
Reopening, as the current variants are simply placeholders. This issue will automatically close after I merge the parenchyma branch.

**Comment by jonysy** [comment]
Reopening, as the current variants are simply placeholders. This issue will automatically close after I merge the parenchyma branch.
